name: Social Automation

on:
  schedule:
    - cron: '*/15 * * * *' # Har 15 minute mein chalega
  workflow_dispatch: # Manual run karne ke liye

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Packages
        run: pip install -r requirements.txt

      - name: Run Script
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_TOKEN_BILLIONAIRE: ${{ secrets.YT_TOKEN_BILLIONAIRE }}
          YT_TOKEN_AI_SALES: ${{ secrets.YT_TOKEN_AI_SALES }}
          FB_USER_TOKEN: ${{ secrets.FB_USER_TOKEN }}
          FB_PAGE_ID_BILLIONAIRE: ${{ secrets.FB_PAGE_ID_BILLIONAIRE }}
          FB_PAGE_ID_AI_SALES: ${{ secrets.FB_PAGE_ID_AI_SALES }}
        run: python main.py
        
